# -*- coding: utf-8 -*-
import time

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow

# from grade_statistics.src.main import MainUi
# from grade_statistics.src.vals.sqls import *
#
# from grade_statistics.src.vals.db import *
# import grade_statistics.src.vals.global_var as gl
import requests
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 30, 641, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(27)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setMidLineWidth(0)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(260, 140, 181, 31))
        font = QtGui.QFont("Microsoft YaHei")
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 140, 91, 31))
        font = QtGui.QFont("Microsoft YaHei")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 190, 91, 31))
        font = QtGui.QFont("Microsoft YaHei")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 190, 181, 31))
        font = QtGui.QFont("Microsoft YaHei")
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 250, 81, 31))
        font = QtGui.QFont("Microsoft YaHei")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.registerButton = QtWidgets.QPushButton(self.centralwidget)
        self.registerButton.setGeometry(QtCore.QRect(290, 280, 81, 31))
        font = QtGui.QFont("Microsoft YaHei")
        font.setPointSize(12)
        self.registerButton.setFont(font)
        self.registerButton.setObjectName("registerButton")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 410, 241, 31))
        font = QtGui.QFont("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(210, 415, 411, 21))
        font = QtGui.QFont("Microsoft YaHei")
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 225, 211, 20))
        self.label_6.setObjectName("label_6")
        self.label_6.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.centralwidget.setStyleSheet('''
                    QLabel#label_6{
                        color:red;
                    }
                    #pushButton{background-color:#2c7adf;color:#fff;border:none;border-radius:4px;}
                    #pushButton:hover{background-color:#2c8adf;}
                ''')

        self.centralwidget.setStyleSheet('''
                           QLabel#label_6{
                               color:red;
                           }
                           #registerButton{background-color:#2c7adf;color:#fff;border:none;border-radius:4px;}
                           #registerButton:hover{background-color:#2c8adf;}
                       ''')


        self.pushButton.clicked.connect(lambda: self.btn_clicked(MainWindow))
        self.lineEdit.textEdited.connect(self.btn_clicked2)
        self.lineEdit_2.textEdited.connect(self.btn_clicked2)
        self.lineEdit_2.returnPressed.connect(lambda: self.btn_clicked(MainWindow))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "达人管家"))
        self.label.setText(_translate("MainWindow", "欢迎来到达人管家"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请输入用户名"))
        self.label_2.setText(_translate("MainWindow", "用户名："))
        self.label_3.setText(_translate("MainWindow", "密码："))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.pushButton.setText(_translate("MainWindow", "登录"))
        self.registerButton.setText(_translate("MainWindow", "注册"))

        # self.label_6.setText(_translate("MainWindow", ""))

    def btn_clicked2(self):
        self.label_6.setText("")

    def btn_clicked(self,MainWindow):
        """
        管理员登录
        :return:
        """
        self.label_6.setText("正在登录...")
        self.pushButton.setDisabled(True)
        QApplication.processEvents()


        headers = {
            "Content-Type":"application/x-www-form-urlencoded"
        }

        username = self.lineEdit.text()
        password = self.lineEdit_2.text()

        data = {
            "open_id":username,
            "password":password,
        }
        response = requests.post("http://106.52.44.49:504/api/login", headers=headers, data=data)

        if response.status_code != 200:
            self.label_6.setText("登录失败")
            self.pushButton.setEnabled(True)
            return

        if response.json()['code'] != 0:
            self.label_6.setText("登录失败" + response.json()['msg'])
            self.pushButton.setEnabled(True)
            return



        print(response.json())
        self.label_6.setText("登录成功" + "vip 时间" +str(response.json()['data']['vipTime']) )

        # result = sql_execute(login(username, password))
        # if len(result) == 0:
        #     self.label_6.setText("登录失败：用户名或密码错误")
        #     self.pushButton.setDisabled(False)
        # else:
        # self.label_6.setText("登录成功！")
        # gl.gl_user = result[0]
        # self.main = MainUi()
        #self.main.show()
        # gl.LOGIN_WINDOW = aw
        #MainWindow.hide()
        # self.main.setWindowTitle('欢迎来到达人管家')
        # print(result)


if __name__ == "__main__":
    import sys

    App = QApplication(sys.argv)  # 创建QApplication对象，作为GUI主程序入口
    aw = Ui_MainWindow()  # 创建主窗体对象，实例化Ui_MainWindow
    w = QMainWindow()  # 实例化QMainWindow类
    aw.setupUi(w)  # 主窗体对象调用setupUi方法，对QMainWindow对象进行设置
    w.show()  # 显示主窗体
    w.setWindowTitle('达人管家')
    sys.exit(App.exec_())  # 循环中等待退出程序